@startuml

title Aktorok - szerepkörök

skinparam actorStyle awesome
left to right direction

"Teljeskörű \nfelhasználó" as SuperUser #PaleTurquoise
"Vezető" as User #LightCyan
"Felhasználók" as Users
"Rendszergazda" as Admin #LightBlue

    Admin -|> SuperUser
    note top of Admin
        rendszergazda felhasználó, mely teljes
        üzemeltetési jogkörrel rendelkezik, az
        alkalmazást nem használja a napi munkában
    end note
    User -|> Users
    note right of User
        az elsődleges felhasználó, mely feladata
        a szervezeti hierarchiából adott
        személyek keresése és azok új/meglévő
        eseményhez rendelése
    end note
    SuperUser -|> User
    note right of SuperUser
        (Titkár/adminisztrátor) a Vezető felhasználón
        felül képes új személyek felvételére, szervezeti
        hierarchia bővítésére, szervezetek áthelyezésére, 
        személyek hierarchiában áthelyezésére, a személyek
        adatainak módosítására
    end note
    note bottom of Users
        bármely típusú, a megoldással kapcsolatba
        lépő felhasználót szimbolizál, mely képes
        a megoldásba belépni és a szerepköre szerinti
        műveleteket elvégezni
    end note



@enduml