@startuml

title Magas szintű használati esetek

skinparam actorStyle awesome
left to right direction

"Teljeskörű \nfelhasználó" as SuperUser
"Vezető" as User
"Felhasználók" as Users
"Rendszergazda" as Admin

(Belépés) as Login
rectangle "Szervezet" {
    (Szervezet böngészése) as DisplayHierarchy
    (Szervezeti szint \nlétrehozása) as CreateOrg
    (Szervezeti szint \nszerkesztése/ \náthelyezée) as EditOrg
    (Szervezeti szint \ntörlése) as DeleteOrg
}
rectangle "Személy" {
    (Személylista böngészése) as BrowsePeople
    (Személy megtekintése) as DisplayPerson
    (Személy szerkesztése) as EditPerson
    (Személy létrehozása) as CreatePerson
    (Személy szervezeti \n szinthez \nrendelése) as AssignPerson
    (Személy törlése) as DeletePerson
    (Személy keresése) as SearchPerson
}
rectangle "Esemény" {
    (Esemény létrehozása) as CreateEvent
    (Esemény szerkesztése) as EditEvent
    (Esemény törlése) as DeleteEvent
    (Esemény megtekintése) as DisplayEvent
    (Személy eseményhez \nadása) as AssignPersonEvent
    (Esemélylista böngészése) as BrowseEvents
}

EditPerson -left-|> DisplayPerson
'CreatePerson -up-|> DisplayPerson

Users --> Login
    Admin --|> SuperUser
    SuperUser -right-|> User
    User -|> Users


User -left-> DisplayHierarchy
User --> BrowsePeople
User --> DisplayPerson
User --> EditPerson
User -> SearchPerson
User -up-> DisplayEvent
User -up-> AssignPersonEvent
User -> BrowseEvents


SuperUser -left-> CreateOrg
SuperUser -left-> EditOrg
SuperUser -> CreatePerson
SuperUser -> AssignPerson
SuperUser -up-> DeleteEvent
SuperUser -up-> CreateEvent
SuperUser -up-> EditEvent

Admin -up-> DeleteOrg
Admin -up-> DeletePerson




@enduml