@startuml

title Magas szintű használati esetek

skinparam actorStyle awesome
left to right direction

"Teljeskörű \nfelhasználó" as SuperUser #PaleTurquoise
"Vezető" as User #LightCyan
"Felhasználók" as Users
"Rendszergazda" as Admin #LightBlue

rectangle "Szervezetek kezelése" {
    (Szervezeti szint \nlétrehozása) as CreateOrg #PaleTurquoise
    (Szervezeti szint \nszervezeti szinthez\nrendelése) as LinkOrg #PaleTurquoise
    (Szervezetfa böngészése) as BrowseHierarchy #LightCyan
    (Szervezeti szint \nszerkesztése) as EditOrg #PaleTurquoise
    (Szervezeti szint \ntörlése) as DeleteOrg #LightBlue
    (Személy szervezeti \n szinthez \nrendelése) as AssignPerson #PaleTurquoise
}
rectangle "Személyek kezelése" {
    (Személy létrehozása) as CreatePerson #PaleTurquoise
    (Személylista böngészése) as BrowsePeople #LightCyan
    (Személy keresése) as SearchPerson #LightCyan
    (Személy szerkesztése) as EditPerson #LightCyan
    (Személy megtekintése) as DisplayPerson #LightCyan
    (Személy törlése) as DeletePerson #LightBlue
'    (Személy személyhez \nrendelése) as LinkPerson #LightCyan
}
rectangle "Események kezelése" {
    (Esemény létrehozása) as CreateEvent #PaleTurquoise
    (Esemény szerkesztése) as EditEvent #PaleTurquoise
    (Esemény törlése) as DeleteEvent #PaleTurquoise
    (Esemény megtekintése) as DisplayEvent #LightCyan
    (Személy eseményhez \nrendelése, hozzárendelés \ntörlése) as AssignPersonEvent #LightCyan
    (Esemélylista böngészése) as BrowseEvents #LightCyan
}
rectangle "Felhasználókezelés" {
    (Bejelentkezés) as Login
    (Kijelentkezés) as Logout
    (Jelszóváltoztatás) as ChangePassword
    (Felhasználó felvitele) as AddUser #LightBlue
    (Felhasználólista böngészése) as BrowseUsers #LightBlue
    (Felhasználó szerepkörbe \nrakása) as AssignUser #LightBlue
}



EditPerson -left-|> DisplayPerson
'CreatePerson -up-|> DisplayPerson

Admin ----|> SuperUser
SuperUser -right-|> User
User -left-|> Users

Users -up-> Login
Users -up-> Logout
Users -up-> ChangePassword

' User ***************
User -left-> BrowsePeople
User -left-> DisplayPerson
User -left-> EditPerson
'User -left-> LinkPerson
User -left-> SearchPerson

User ---up-> BrowseHierarchy

User ---> DisplayEvent
User ---> AssignPersonEvent
User ---> BrowseEvents



' SuperUser ************
SuperUser -up-> CreatePerson
SuperUser -up-> AssignPerson

SuperUser ---up-> CreateOrg
SuperUser ---up-> EditOrg
SuperUser ---up-> LinkOrg

SuperUser ---> DeleteEvent
SuperUser ---> CreateEvent
SuperUser ---> EditEvent



' Admin ************
Admin -> DeletePerson

Admin --> DeleteOrg

Admin -up-> AddUser
Admin -up-> BrowseUsers
Admin -up-> AssignUser



@enduml