@startuml

'left to right direction

class Organization {
  -OrganizationID : Int
  -TopLevel : Boolean
  -Name : String
  -FK_OrganizationID : Int
  -Active : Boolean
  -Address : String
  -CreationDate : Date
  -LastModified : Date
  -FK_OrganizationID : Int 
}


class Person {
  -PersonID : Int
  -FirstName : String
  -LastName : String
  -Notes : String
  -PersonalEmail : String
  -Active : Boolean
  -CreationDate : Date
  -LastModified : Date
  -FK_PersonID : Int
}

class PersonToOrganization {
  -FK_PersonID : Int
  -FK_OrganizationID : Int
  -Role : String
  -Email : String
  -Address : String
}


class Event {
  -EventID : Int
  -Name : String
  -Description : String
  -Location : String
  -Date : Date
  -Active : Boolean
  -CreationDate : Date
  -LastModified : Date
}

class RSVP {
  -RSVPID : Int
  -Name : String
}

class PersonToEvent {
  -FK_PersonID : Int
  -FK_EventID : Int
  -FK_RSVPID : Int
  -LastModified : Date
}

class User {
  -UserID : Int
  -Name : String
  -UserRole : Int
}


PersonToOrganization -down-> Person
PersonToOrganization -up-> Organization
PersonToEvent -left-> Person
PersonToEvent -right-> Event
PersonToEvent -up-> RSVP
Organization -> Organization
Person -> Person

@enduml